(* Copyright (C) 1997 The Harlequin Group Limited.  All rights reserved.
 *
 * This file would be automatically generated by the stub generator.
 * This version has been written by hand.
 *
 * Revision Log
 * ------------
 * $Log: __add.sml,v $
 * Revision 1.2  1997/07/03 08:15:44  stephenb
 * [Bug #30029]
 * Update with respect to the change from C to MLWorksCInterface.
 *
 *  Revision 1.1  1997/05/07  09:03:12  stephenb
 *  new unit
 *  [Bug #30030]
 *
 *)

require "add";
require "$.foreign.__mlworks_dynamic_library";
require "$.foreign.__mlworks_c_interface";
require "__add_stub";

structure Add : ADD =
  struct
    type c_int = MLWorksCInterface.Int.int

    val add : c_int * c_int -> c_int = MLWorksDynamicLibrary.bind "add"
  end
