(* Copyright (C) 1997 The Harlequin Group Limited.  All rights reserved.
 *
 * This file should be automatically generated by the stub generator.
 * This version has been written by hand.
 *
 * Revision Log
 * ------------
 * $Log: add.sml,v $
 * Revision 1.2  1997/07/03 08:15:08  stephenb
 * [Bug #30029]
 * Update with respect to the change from C to MLWorksCInterface.
 *
 *  Revision 1.1  1997/04/29  15:26:53  stephenb
 *  new unit
 *  [Bug #30030]
 *
 *)

signature ADD =
  sig
    eqtype c_int

    val add : c_int * c_int -> c_int
  end
