/* Copyright (C) 1997 The Harlequin Group Limited.  All rights reserved.
 *
 * This file should be generated by the stub generator
 * This version has been written by hand.
 *
 * Revision Log
 * ------------
 * $Log: add_stub.c,v $
 * Revision 1.2  1997/06/30 10:47:13  stephenb
 * [Bug #30029]
 * Propagate changes made to mlw_ci.h to here.
 *
 * Revision 1.1  1997/04/29  15:27:00  stephenb
 * new unit
 * [Bug #30030]
 *
 */

#include "add.h"
#include "mlw_ci.h"


static mlw_val mlw_stub_add(mlw_val arg)
{
  int i= mlw_ci_int_to_int(mlw_arg(arg, 0));
  int j= mlw_ci_int_to_int(mlw_arg(arg, 1));
  int r= add(i, j);
  return mlw_ci_int_from_int(r);
}



mlw_ci_export void mlw_stub_init_add(void)
{
  mlw_ci_register_function("add", mlw_stub_add);
}
