/* Copyright 2013 Ravenbrook Limited <http://www.ravenbrook.com/>.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This file should be generated by the stub generator
 * This version has been written by hand.
 *
 * Revision Log
 * ------------
 * $Log: add_stub.c,v $
 * Revision 1.2  1997/06/30 10:47:13  stephenb
 * [Bug #30029]
 * Propagate changes made to mlw_ci.h to here.
 *
 * Revision 1.1  1997/04/29  15:27:00  stephenb
 * new unit
 * [Bug #30030]
 *
 */

#include "add.h"
#include "mlw_ci.h"


static mlw_val mlw_stub_add(mlw_val arg)
{
  int i= mlw_ci_int_to_int(mlw_arg(arg, 0));
  int j= mlw_ci_int_to_int(mlw_arg(arg, 1));
  int r= add(i, j);
  return mlw_ci_int_from_int(r);
}



mlw_ci_export void mlw_stub_init_add(void)
{
  mlw_ci_register_function("add", mlw_stub_add);
}
