# Windows makefile for ../execute.c.
# 
# Copyright (C) 1999 Harlequin Group plc.  All rights reserved.
#
# $Log: Makefile,v $
# Revision 1.1  1999/03/18 12:05:21  daveb
# new unit
# Makefile for execute.c.
#

execute: ../execute.c
	cl $< -o $@
