(*
 * Copyright (c) 1998, Harlequin Group plc
 * All rights reserved
 *
 * $Log: load.l,v $
 * Revision 1.1  1998/08/06 10:36:09  jont
 * new unit
 * Lego test application
 *
 *
 *)
Include "basics.l";
Include "basics1.l";
Include "expressions.l";
Include "values.l";
Include "bops.l";
Include "semantics.l";
Include "equiv.l";
Include "lift_lemma.l";
Include "subst_theorem.l";
Include "beta_theorem.l";
Include "drop.l";
