(* Copyright (C) 1997 The Harlequin Group Limited.  All rights reserved.
 *
 * This file should be generated by a stub-generator from <ndbm.h>
 * The current version has been written by hand.
 * 
 * Revision Log
 * ------------
 * $Log: __ndbm_stub.sml,v $
 * Revision 1.2  1997/06/30 10:40:39  stephenb
 * [Bug #30029]
 * The previous version used the signatures/structures from
 * the prototype version the new FI.  This version uses the
 * signatures/structures that a customer will see.
 *
 *  Revision 1.1  1997/05/07  09:06:10  stephenb
 *  new unit
 *  [Bug #30030]
 *
 *)

require "$.foreign.__mlworks_dynamic_library";

val _ = MLWorksDynamicLibrary.openLibrary ("ndbm_stub.so", "mlw_stub_init_ndbm");
