(* Copyright (C) 1997 The Harlequin Group Limited.  All rights reserved.
 *
 * This file should be generated by a stub-generator from <dirent.h>
 * The current version has been written by hand.
 * 
 * Revision Log
 * ------------
 * $Log: __dirent_stub.sml,v $
 * Revision 1.2  1997/07/03 10:09:03  stephenb
 * Automatic checkin:
 * changed attribute _comment to ' *  '
 *
 *)

require "$.foreign.__mlworks_dynamic_library";

val _ = MLWorksDynamicLibrary.openLibrary ("dirent_stub.so", "mlw_stub_init_dirent");
