(* Copyright (C) 1997 The Harlequin Group Limited.  All rights reserved.
 *
 * This file would be automatically generated by the stub generator
 * This version has been generated by hand
 *
 * Revision Log
 * ------------
 * $Log: __add_stub.sml,v $
 * Revision 1.2  1997/06/30 10:47:46  stephenb
 * [Bug #30029]
 * Update with respect to the change from C to MLWorksCInterface.
 *
 *  Revision 1.1  1997/04/29  15:27:38  stephenb
 *  new unit
 *  [Bug #30030]
 *
 *)

require "$.foreign.__mlworks_dynamic_library";

val _ = MLWorksDynamicLibrary.openLibrary ("add_stub.so", "mlw_stub_init_add");
