#!/bin/sh
#
# Copyright (c) 1998, Harlequin Group plc
# All rights reserved
#
# $Log: RUN_SOME,v $
# Revision 1.1  1998/05/28 15:34:13  jont
# new unit
# Adding scripts to run applications/tests into hope
#
#
MLWORKS_PERVASIVE=/u/sml/MLW/src/pervasive;export MLWORKS_PERVASIVE
MLWORKS_SRC_PATH=/u/sml/MLW/src;export MLWORKS_SRC_PATH
XUSERFILESEARCHPATH=/u/sml/MLW/src/app-defaults/%N%C;export XUSERFILESEARCHPATH
RUN_SOME.sh $*
